### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by mackensen** [tkotosz/behat-screenshot-image-driver-uploadpie#2]
This has stopping working for me; all failed steps generate the following message instead of a URL: "Screenshot has been taken. Open image at 3145728".

**Comment by guillaumeray** [comment]
I have the same error

**Comment by tkotosz** [comment]
weird, will have a look (I just scheduled an inspection on scrutinizer to see if the tests are failing as well)

**Comment by tkotosz** [comment]
it seems scrutinizer can confirm that this is broken: https://scrutinizer-ci.com/g/tkotosz/behat-screenshot-image-driver-uploadpie/inspections/cce797f9-0293-4551-80a3-51f0fc316056
I will check the issue soon.

**Comment by guillaumeray** [comment]
Thanks !

**Comment by guillaumeray** [comment]
If you want to create a new image driver in your repository i have changed some of the UploadPieApi.php code with the code below. I use http://uploads.im/ api, which is very good and easy.

The host is very cool and free
"Uploads.im is simple, fast and reliable service to upload your images."
"The maximum size of a single image – 10MB. The number of images and their period of storage on the server is not limited."

```php
<?php

namespace Bex\Behat\ScreenshotExtension\Driver\Service;

use Buzz\Client\Curl;
use Buzz\Message\Form\FormRequest;
use Buzz\Message\Form\FormUpload;
use Buzz\Message\Response;

class UploadPieApi
{
    const REQUEST_URL = 'http://uploads.im/api';

    /**
     * @var Curl
     */
    private $client;

    /**
     * @param Curl|null $client
     */
    public function __construct(Curl $client = null)
    {
        $this->client = $client ?: new Curl();
    }

    /**
     * @param  string $binaryImage
     * @param  string $filename
     * @param  int    $expire
     *
     * @return Response
     */
    public function call($binaryImage, $filename, $expire)
    {
        $response = new Response();

        $image = new FormUpload();
        $image->setFilename($filename);
        $image->setContent($binaryImage);

        $request = $this->buildRequest($image, $expire);
        $this->client->setOption(CURLOPT_TIMEOUT, 10000);
        $this->client->send($request, $response);

        return $this->processResponse($response);
    }

    /**
     * @param  Response $response
     *
     * @return string
     */
    private function processResponse(Response $response)
    {
        $responseData = json_decode($response->getContent(), true);

        if ($responseData['status_txt'] != 'OK') {
            throw new \RuntimeException('Screenshot upload failed');
        }
        return $responseData['data']['img_url'];
    }

    /**
     * @param  FormUpload $image
     * @param  int        $expire
     *
     * @return FormRequest
     */
    private function buildRequest($image, $expire)
    {
        $request = new FormRequest();
        
        $request->fromUrl(self::REQUEST_URL);
        $request->setField('upload', $image);
        $request->setField('format', 'json');

        return $request;
    }
}
```

**Comment by tkotosz** [comment]
I didn't have time to check the issue today but your solution looks like it can be a separate image driver for the screenshot extension. Feel free to fork this repo and publish it as a separate image driver. You can fork the dummy driver as well to create your own driver if thats better for you. If you don't want to spend time with it then just let me know and I am happy to create a repo for this uploads.im api and publish it as a new package on packagist. :)

**Comment by tkotosz** [comment]
Just to be sure I just checked and I have included the dummy driver and the working drivers in the description of the screenshot extension when we created it: https://github.com/elvetemedve/behat-screenshot/blob/master/README.md#how-to-create-your-own-image-driver so it should be straightforward to create your own driver. :)

**Comment by tkotosz** [comment]
@mackensen @guillaumeray I just checked this issue in the morning and managed to fix it. The fix is included in the last release (v1.0.2). Could you please update the package and check it?

**Comment by guillaumeray** [comment]
Thanks! 
uploadpie image driver works for me ! 
I have not much time, feel free to create a new repo for uploads.im/ image driver, and push it as a new package for your extension :)

**Comment by tkotosz** [comment]
cool, good to hear that... (I will do the new repo for the uploads.im driver when I will have some free time)
